// Typed client for our FastAPI backend. Every authenticated call carries the signed-in
// user's access token (from react-auth's getAccessToken, which refreshes transparently).
//
// Paths are `/api/v1/*` — see memory-bank/standards/api-conventions.md.
import { env } from "../env";

export type Profile = {
  user_sub: string;
  handle: string | null;
  collection_visibility: "private" | "link" | "public";
  default_currency: string;
  condition_scale: "tcg" | "cardmarket";
  // Platform-owned, read-only here — edited in the platform's own /account.
  email: string | null;
  username: string | null;
  enriched: boolean;
};

export type ProfilePatch = Partial<
  Pick<Profile, "handle" | "collection_visibility" | "default_currency" | "condition_scale">
>;

export type ClientEvent = {
  level?: "debug" | "info" | "warning";
  message: string;
  component?: string;
  context?: Record<string, unknown>;
};

/** The one error shape. `code` is stable and safe to branch on; `message` may change. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
    readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = "ApiError";
  }
}

type TokenGetter = () => Promise<string | null>;

let tokenGetter: TokenGetter = async () => null;
/** Registered once by the auth layer so modules like ErrorBoundary can report without
 *  threading a token getter through the whole component tree. */
export function registerTokenGetter(getter: TokenGetter): void {
  tokenGetter = getter;
}

async function request(path: string, init?: RequestInit, getToken?: TokenGetter): Promise<Response> {
  const token = await (getToken ?? tokenGetter)();
  const res = await fetch(`${env.backendUrl}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  });
  if (!res.ok) {
    let code = "error";
    let message = `${init?.method ?? "GET"} ${path} → ${res.status}`;
    let details: Record<string, unknown> = {};
    try {
      const body = await res.json();
      if (body?.error) {
        code = body.error.code ?? code;
        message = body.error.message ?? message;
        details = body.error.details ?? {};
      }
    } catch {
      // Non-JSON error body — keep the generic message rather than masking the status.
    }
    throw new ApiError(res.status, code, message, details);
  }
  return res;
}

/**
 * Public catalog reads. Deliberately sends **no** Authorization header.
 *
 * `/cards` and `/sets` are cacheable and must never vary on the caller
 * (api-conventions.md). Attaching a token to a request whose response is shared would put a
 * per-user header on a cacheable response for no benefit — the backend ignores it anyway,
 * because these routes take no Principal at all.
 */
async function publicRequest(path: string): Promise<Response> {
  const res = await fetch(`${env.backendUrl}${path}`, {
    headers: { "Content-Type": "application/json" },
  });
  if (!res.ok) {
    let code = "error";
    let message = `GET ${path} → ${res.status}`;
    let details: Record<string, unknown> = {};
    try {
      const body = await res.json();
      if (body?.error) {
        code = body.error.code ?? code;
        message = body.error.message ?? message;
        details = body.error.details ?? {};
      }
    } catch {
      // Non-JSON error body — keep the generic message rather than masking the status.
    }
    throw new ApiError(res.status, code, message, details);
  }
  return res;
}

function qs(params: Record<string, string | number | string[] | undefined>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === "") continue;
    // Repeated params OR within an attribute — the filter algebra the API expects.
    if (Array.isArray(value)) value.forEach((v) => search.append(key, v));
    else search.append(key, String(value));
  }
  const encoded = search.toString();
  return encoded ? `?${encoded}` : "";
}

export type MatchKind =
  | "exact_name" | "name_prefix" | "word_prefix"
  | "collector_number" | "set_code" | "infix";

export type PrintingView = {
  printing_id: string;
  rarity: string;
  finish: string;
  language: string;
  edition: string;
  image_url: string | null;
  /** `"{name} — {set} {rarity}"`, generated by the backend so it cannot drift per component. */
  alt_text: string;
};

export type CardSearchResult = {
  card_id: string;
  name: string;
  set_code: string;
  collector_number: string;
  card_type: string;
  element: string | null;
  primary_printing: PrintingView | null;
  printing_count: number;
  match_kind: MatchKind;
};

export type CardDetail = {
  card_id: string;
  name: string;
  set_code: string;
  set_name: string;
  collector_number: string;
  card_type: string;
  element: string | null;
  rune_type: string | null;
  subtype: string | null;
  attack: number | null;
  defence: number | null;
  spirit_cost: Record<string, number> | null;
  rules_text: string | null;
  flavour_text: string | null;
  artist: string | null;
  printings: PrintingView[];
};

/** No completion field, on purpose — that is per-user and comes from bolt 004. */
export type SetSummary = {
  code: string;
  name: string;
  series: string | null;
  released_on: string | null;
  /** The declared printed size — the completion denominator. */
  card_count: number;
  /** What we have actually imported. Below `card_count` means an incomplete catalog. */
  imported_count: number;
  logo_asset_url: string | null;
};

export type SetChecklistEntry = {
  card_id: string;
  collector_number: string;
  name: string;
  element: string | null;
  card_type: string;
  printings: PrintingView[];
};

export type Paged<T> = { items: T[]; next_cursor: string | null; total: number };

export type CatalogHealth = {
  sources: {
    source: string;
    display_name: string;
    requires_network: boolean;
    last_run_id: string | null;
    last_status: string | null;
    last_started_at: string | null;
    staleness: {
      last_success_at: string | null;
      age_hours: number | null;
      state: "fresh" | "ageing" | "stale" | "never_run";
    };
  }[];
  sets_below_coverage: {
    set_code: string; expected: number; imported: number; missing_count: number;
  }[];
  latest_run_id: string | null;
  rejections: { reason_code: string; count: number; example_source_ref: string }[];
};

export type SearchFilters = {
  set_code?: string[];
  element?: string[];
  card_type?: string[];
  rarity?: string[];
};

export async function searchCards(
  term: string,
  filters: SearchFilters = {},
  limit = 25,
): Promise<Paged<CardSearchResult>> {
  const path = `/api/v1/cards${qs({ q: term, limit, ...filters })}`;
  return (await (await publicRequest(path)).json()) as Paged<CardSearchResult>;
}

export async function fetchCard(cardId: string): Promise<CardDetail> {
  return (await (await publicRequest(`/api/v1/cards/${cardId}`)).json()) as CardDetail;
}

export async function fetchSets(series?: string): Promise<{ items: SetSummary[] }> {
  return (await (await publicRequest(`/api/v1/sets${qs({ series })}`)).json()) as {
    items: SetSummary[];
  };
}

export async function fetchSetChecklist(
  code: string,
): Promise<{ set: SetSummary } & Paged<SetChecklistEntry>> {
  const res = await publicRequest(`/api/v1/sets/${encodeURIComponent(code)}`);
  return (await res.json()) as { set: SetSummary } & Paged<SetChecklistEntry>;
}

// --- Inventory writes (bolt 004, plus /adjust from ADR-005) --------------------------

export type InventoryItemView = {
  id: string;
  printing_id: string;
  condition: string;
  quantity: number;
  is_graded: boolean;
  updated_at: string;
};

export type AddInventoryResult = {
  item: InventoryItemView;
  /** True when the add folded into an existing row. Shown as "now 3" so a collector does not
   *  wonder where their new row went. */
  merged: boolean;
};

export async function addInventory(
  body: { printing_id: string; condition: string; quantity: number },
  getToken?: TokenGetter,
): Promise<AddInventoryResult> {
  const res = await request(
    "/api/v1/inventory",
    { method: "POST", body: JSON.stringify(body) },
    getToken,
  );
  return (await res.json()) as AddInventoryResult;
}

export type AdjustResult = { item_id: string; quantity: number; deleted: boolean };

/**
 * Change a quantity by a delta — the undo primitive, ADR-005.
 *
 * `expected_quantity` means **what the caller believes, from its own record of what it did** —
 * not what it just read. Fetching the row to fill this field reinstates the read-then-write the
 * endpoint exists to avoid, with extra steps and a false sense of safety.
 *
 * A `409` (`inventory_item_changed`) means somebody else moved the row; its `details` carry
 * `expected` and `actual` so the refusal can say what it found.
 */
export async function adjustInventory(
  itemId: string,
  body: { delta: number; expected_quantity: number },
  getToken?: TokenGetter,
): Promise<AdjustResult> {
  const res = await request(
    `/api/v1/inventory/${encodeURIComponent(itemId)}/adjust`,
    { method: "POST", body: JSON.stringify(body) },
    getToken,
  );
  return (await res.json()) as AdjustResult;
}

/** Owner-scoped holdings for one printing — how the session learns a baseline quantity. */
export async function fetchHoldingsFor(
  printingId: string,
  getToken?: TokenGetter,
): Promise<Paged<InventoryItemView>> {
  const res = await request(
    `/api/v1/inventory${qs({ printing_id: printingId, limit: 50 })}`,
    undefined,
    getToken,
  );
  return (await res.json()) as Paged<InventoryItemView>;
}

/** Operator-only, so this one *does* carry the token. */
export async function fetchCatalogHealth(getToken?: TokenGetter): Promise<CatalogHealth> {
  const res = await request("/api/v1/admin/catalog/health", undefined, getToken);
  return (await res.json()) as CatalogHealth;
}

export async function fetchProfile(getToken?: TokenGetter): Promise<Profile> {
  return (await (await request("/api/v1/me", undefined, getToken)).json()) as Profile;
}

export async function updateProfile(patch: ProfilePatch, getToken?: TokenGetter): Promise<Profile> {
  const res = await request(
    "/api/v1/me",
    { method: "PATCH", body: JSON.stringify(patch) },
    getToken,
  );
  return (await res.json()) as Profile;
}

/**
 * Relay a client event into logging. The browser has no `logs:write` scope and must never
 * reach logs-api directly — the backend stamps the validated caller, so identity cannot be
 * spoofed. Best-effort by design: reporting a problem must not create one.
 */
export async function reportClientEvent(event: ClientEvent): Promise<void> {
  try {
    await request("/api/v1/events", { method: "POST", body: JSON.stringify(event) });
  } catch {
    // Intentionally swallowed.
  }
}
